export const ui = {
  heading: 'Unfold your musical journey',
  subHeading: 'Explore, discover, and soundtrack your life with out vast song collection that spans genres and eras',
  searchLabel: 'Search for songs by artist or title',
  filterBy: 'Filter by level',
  hideFilter: 'Hide filter',
  favoriteLoadingError: 'Something went wrong with loading favorites, retrying...',
  errorLoadingSongs: 'Something went wrong with loading songs, retrying...',
  tryAgain: 'Try again',
  notFound: 'No songs found',
  fetchAll: 'Show all songs',
  favoriteDeletingError: 'Something went wrong with deleting favorite, please try again',
  favoriteAddingError: 'Something went wrong with adding favorite, please try again',
  filter: 'Filter',
  level: 'Level',
  deleteFavorite: 'Remove from favorites',
  addFavorite: 'Add to favorites',
  loading: 'Loading',
  ariaLive: {
    loadingSongs: 'Loading songs',
    favAdded: 'Added to favorites',
    favRemoved: 'Removed from favorites',
    favsLoaded: 'Favorites loaded',
    scrollToLoadMore: 'scroll down to load more',
    songs: 'songs',
    song: 'song',
    found: 'Found',
  },
}
